/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterClientRouteImport } from './routes/register-client'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FTokenRouteImport } from './routes/f.$token'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as FTokenSuccessRouteImport } from './routes/f.$token_.success'
import { Route as ClientClientProfileRouteImport } from './routes/_client/client/profile'
import { Route as ClientClientChatRouteImport } from './routes/_client/client/chat'
import { Route as ClientClientCalendarRouteImport } from './routes/_client/client/calendar'
import { Route as AuthedDashboardVisitsIndexRouteImport } from './routes/_authed/dashboard/visits/index'
import { Route as AuthedDashboardTreatmentsIndexRouteImport } from './routes/_authed/dashboard/treatments/index'
import { Route as AuthedDashboardSubmissionsIndexRouteImport } from './routes/_authed/dashboard/submissions/index'
import { Route as AuthedDashboardStaffIndexRouteImport } from './routes/_authed/dashboard/staff/index'
import { Route as AuthedDashboardSettingsIndexRouteImport } from './routes/_authed/dashboard/settings/index'
import { Route as AuthedDashboardFormsIndexRouteImport } from './routes/_authed/dashboard/forms/index'
import { Route as AuthedDashboardClientsIndexRouteImport } from './routes/_authed/dashboard/clients/index'
import { Route as AuthedDashboardCalendarIndexRouteImport } from './routes/_authed/dashboard/calendar/index'
import { Route as AuthedDashboardVisitsVisitIdRouteImport } from './routes/_authed/dashboard/visits/$visitId'
import { Route as AuthedDashboardSubmissionsSubmissionIdRouteImport } from './routes/_authed/dashboard/submissions/$submissionId'
import { Route as AuthedDashboardFormsNewRouteImport } from './routes/_authed/dashboard/forms/new'
import { Route as AuthedDashboardClientsClientIdRouteImport } from './routes/_authed/dashboard/clients/$clientId'
import { Route as AuthedDashboardFormsFormIdEditRouteImport } from './routes/_authed/dashboard/forms/$formId/edit'

const RegisterClientRoute = RegisterClientRouteImport.update({
  id: '/register-client',
  path: '/register-client',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FTokenRoute = FTokenRouteImport.update({
  id: '/f/$token',
  path: '/f/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const FTokenSuccessRoute = FTokenSuccessRouteImport.update({
  id: '/f/$token_/success',
  path: '/f/$token/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientClientProfileRoute = ClientClientProfileRouteImport.update({
  id: '/client/profile',
  path: '/client/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientClientChatRoute = ClientClientChatRouteImport.update({
  id: '/client/chat',
  path: '/client/chat',
  getParentRoute: () => ClientRoute,
} as any)
const ClientClientCalendarRoute = ClientClientCalendarRouteImport.update({
  id: '/client/calendar',
  path: '/client/calendar',
  getParentRoute: () => ClientRoute,
} as any)
const AuthedDashboardVisitsIndexRoute =
  AuthedDashboardVisitsIndexRouteImport.update({
    id: '/visits/',
    path: '/visits/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardTreatmentsIndexRoute =
  AuthedDashboardTreatmentsIndexRouteImport.update({
    id: '/treatments/',
    path: '/treatments/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardSubmissionsIndexRoute =
  AuthedDashboardSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardStaffIndexRoute =
  AuthedDashboardStaffIndexRouteImport.update({
    id: '/staff/',
    path: '/staff/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardSettingsIndexRoute =
  AuthedDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardFormsIndexRoute =
  AuthedDashboardFormsIndexRouteImport.update({
    id: '/forms/',
    path: '/forms/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardClientsIndexRoute =
  AuthedDashboardClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardCalendarIndexRoute =
  AuthedDashboardCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardVisitsVisitIdRoute =
  AuthedDashboardVisitsVisitIdRouteImport.update({
    id: '/visits/$visitId',
    path: '/visits/$visitId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardSubmissionsSubmissionIdRoute =
  AuthedDashboardSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardFormsNewRoute = AuthedDashboardFormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardClientsClientIdRoute =
  AuthedDashboardClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardFormsFormIdEditRoute =
  AuthedDashboardFormsFormIdEditRouteImport.update({
    id: '/forms/$formId/edit',
    path: '/forms/$formId/edit',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/register-client': typeof RegisterClientRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/f/$token': typeof FTokenRoute
  '/client/calendar': typeof ClientClientCalendarRoute
  '/client/chat': typeof ClientClientChatRoute
  '/client/profile': typeof ClientClientProfileRoute
  '/f/$token/success': typeof FTokenSuccessRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/clients/$clientId': typeof AuthedDashboardClientsClientIdRoute
  '/dashboard/forms/new': typeof AuthedDashboardFormsNewRoute
  '/dashboard/submissions/$submissionId': typeof AuthedDashboardSubmissionsSubmissionIdRoute
  '/dashboard/visits/$visitId': typeof AuthedDashboardVisitsVisitIdRoute
  '/dashboard/calendar/': typeof AuthedDashboardCalendarIndexRoute
  '/dashboard/clients/': typeof AuthedDashboardClientsIndexRoute
  '/dashboard/forms/': typeof AuthedDashboardFormsIndexRoute
  '/dashboard/settings/': typeof AuthedDashboardSettingsIndexRoute
  '/dashboard/staff/': typeof AuthedDashboardStaffIndexRoute
  '/dashboard/submissions/': typeof AuthedDashboardSubmissionsIndexRoute
  '/dashboard/treatments/': typeof AuthedDashboardTreatmentsIndexRoute
  '/dashboard/visits/': typeof AuthedDashboardVisitsIndexRoute
  '/dashboard/forms/$formId/edit': typeof AuthedDashboardFormsFormIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/register-client': typeof RegisterClientRoute
  '/f/$token': typeof FTokenRoute
  '/client/calendar': typeof ClientClientCalendarRoute
  '/client/chat': typeof ClientClientChatRoute
  '/client/profile': typeof ClientClientProfileRoute
  '/f/$token/success': typeof FTokenSuccessRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/clients/$clientId': typeof AuthedDashboardClientsClientIdRoute
  '/dashboard/forms/new': typeof AuthedDashboardFormsNewRoute
  '/dashboard/submissions/$submissionId': typeof AuthedDashboardSubmissionsSubmissionIdRoute
  '/dashboard/visits/$visitId': typeof AuthedDashboardVisitsVisitIdRoute
  '/dashboard/calendar': typeof AuthedDashboardCalendarIndexRoute
  '/dashboard/clients': typeof AuthedDashboardClientsIndexRoute
  '/dashboard/forms': typeof AuthedDashboardFormsIndexRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsIndexRoute
  '/dashboard/staff': typeof AuthedDashboardStaffIndexRoute
  '/dashboard/submissions': typeof AuthedDashboardSubmissionsIndexRoute
  '/dashboard/treatments': typeof AuthedDashboardTreatmentsIndexRoute
  '/dashboard/visits': typeof AuthedDashboardVisitsIndexRoute
  '/dashboard/forms/$formId/edit': typeof AuthedDashboardFormsFormIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_client': typeof ClientRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/register-client': typeof RegisterClientRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/f/$token': typeof FTokenRoute
  '/_client/client/calendar': typeof ClientClientCalendarRoute
  '/_client/client/chat': typeof ClientClientChatRoute
  '/_client/client/profile': typeof ClientClientProfileRoute
  '/f/$token_/success': typeof FTokenSuccessRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/clients/$clientId': typeof AuthedDashboardClientsClientIdRoute
  '/_authed/dashboard/forms/new': typeof AuthedDashboardFormsNewRoute
  '/_authed/dashboard/submissions/$submissionId': typeof AuthedDashboardSubmissionsSubmissionIdRoute
  '/_authed/dashboard/visits/$visitId': typeof AuthedDashboardVisitsVisitIdRoute
  '/_authed/dashboard/calendar/': typeof AuthedDashboardCalendarIndexRoute
  '/_authed/dashboard/clients/': typeof AuthedDashboardClientsIndexRoute
  '/_authed/dashboard/forms/': typeof AuthedDashboardFormsIndexRoute
  '/_authed/dashboard/settings/': typeof AuthedDashboardSettingsIndexRoute
  '/_authed/dashboard/staff/': typeof AuthedDashboardStaffIndexRoute
  '/_authed/dashboard/submissions/': typeof AuthedDashboardSubmissionsIndexRoute
  '/_authed/dashboard/treatments/': typeof AuthedDashboardTreatmentsIndexRoute
  '/_authed/dashboard/visits/': typeof AuthedDashboardVisitsIndexRoute
  '/_authed/dashboard/forms/$formId/edit': typeof AuthedDashboardFormsFormIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/logout'
    | '/register'
    | '/register-client'
    | '/dashboard'
    | '/f/$token'
    | '/client/calendar'
    | '/client/chat'
    | '/client/profile'
    | '/f/$token/success'
    | '/dashboard/'
    | '/dashboard/clients/$clientId'
    | '/dashboard/forms/new'
    | '/dashboard/submissions/$submissionId'
    | '/dashboard/visits/$visitId'
    | '/dashboard/calendar/'
    | '/dashboard/clients/'
    | '/dashboard/forms/'
    | '/dashboard/settings/'
    | '/dashboard/staff/'
    | '/dashboard/submissions/'
    | '/dashboard/treatments/'
    | '/dashboard/visits/'
    | '/dashboard/forms/$formId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/logout'
    | '/register'
    | '/register-client'
    | '/f/$token'
    | '/client/calendar'
    | '/client/chat'
    | '/client/profile'
    | '/f/$token/success'
    | '/dashboard'
    | '/dashboard/clients/$clientId'
    | '/dashboard/forms/new'
    | '/dashboard/submissions/$submissionId'
    | '/dashboard/visits/$visitId'
    | '/dashboard/calendar'
    | '/dashboard/clients'
    | '/dashboard/forms'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/dashboard/submissions'
    | '/dashboard/treatments'
    | '/dashboard/visits'
    | '/dashboard/forms/$formId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_client'
    | '/accept-invite'
    | '/login'
    | '/logout'
    | '/register'
    | '/register-client'
    | '/_authed/dashboard'
    | '/f/$token'
    | '/_client/client/calendar'
    | '/_client/client/chat'
    | '/_client/client/profile'
    | '/f/$token_/success'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/clients/$clientId'
    | '/_authed/dashboard/forms/new'
    | '/_authed/dashboard/submissions/$submissionId'
    | '/_authed/dashboard/visits/$visitId'
    | '/_authed/dashboard/calendar/'
    | '/_authed/dashboard/clients/'
    | '/_authed/dashboard/forms/'
    | '/_authed/dashboard/settings/'
    | '/_authed/dashboard/staff/'
    | '/_authed/dashboard/submissions/'
    | '/_authed/dashboard/treatments/'
    | '/_authed/dashboard/visits/'
    | '/_authed/dashboard/forms/$formId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  RegisterClientRoute: typeof RegisterClientRoute
  FTokenRoute: typeof FTokenRoute
  FTokenSuccessRoute: typeof FTokenSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-client': {
      id: '/register-client'
      path: '/register-client'
      fullPath: '/register-client'
      preLoaderRoute: typeof RegisterClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$token': {
      id: '/f/$token'
      path: '/f/$token'
      fullPath: '/f/$token'
      preLoaderRoute: typeof FTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/f/$token_/success': {
      id: '/f/$token_/success'
      path: '/f/$token/success'
      fullPath: '/f/$token/success'
      preLoaderRoute: typeof FTokenSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/client/profile': {
      id: '/_client/client/profile'
      path: '/client/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/client/chat': {
      id: '/_client/client/chat'
      path: '/client/chat'
      fullPath: '/client/chat'
      preLoaderRoute: typeof ClientClientChatRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/client/calendar': {
      id: '/_client/client/calendar'
      path: '/client/calendar'
      fullPath: '/client/calendar'
      preLoaderRoute: typeof ClientClientCalendarRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_authed/dashboard/visits/': {
      id: '/_authed/dashboard/visits/'
      path: '/visits'
      fullPath: '/dashboard/visits/'
      preLoaderRoute: typeof AuthedDashboardVisitsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/treatments/': {
      id: '/_authed/dashboard/treatments/'
      path: '/treatments'
      fullPath: '/dashboard/treatments/'
      preLoaderRoute: typeof AuthedDashboardTreatmentsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/submissions/': {
      id: '/_authed/dashboard/submissions/'
      path: '/submissions'
      fullPath: '/dashboard/submissions/'
      preLoaderRoute: typeof AuthedDashboardSubmissionsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/staff/': {
      id: '/_authed/dashboard/staff/'
      path: '/staff'
      fullPath: '/dashboard/staff/'
      preLoaderRoute: typeof AuthedDashboardStaffIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/settings/': {
      id: '/_authed/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AuthedDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/forms/': {
      id: '/_authed/dashboard/forms/'
      path: '/forms'
      fullPath: '/dashboard/forms/'
      preLoaderRoute: typeof AuthedDashboardFormsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/clients/': {
      id: '/_authed/dashboard/clients/'
      path: '/clients'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof AuthedDashboardClientsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/calendar/': {
      id: '/_authed/dashboard/calendar/'
      path: '/calendar'
      fullPath: '/dashboard/calendar/'
      preLoaderRoute: typeof AuthedDashboardCalendarIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/visits/$visitId': {
      id: '/_authed/dashboard/visits/$visitId'
      path: '/visits/$visitId'
      fullPath: '/dashboard/visits/$visitId'
      preLoaderRoute: typeof AuthedDashboardVisitsVisitIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/submissions/$submissionId': {
      id: '/_authed/dashboard/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/dashboard/submissions/$submissionId'
      preLoaderRoute: typeof AuthedDashboardSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/forms/new': {
      id: '/_authed/dashboard/forms/new'
      path: '/forms/new'
      fullPath: '/dashboard/forms/new'
      preLoaderRoute: typeof AuthedDashboardFormsNewRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/clients/$clientId': {
      id: '/_authed/dashboard/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/dashboard/clients/$clientId'
      preLoaderRoute: typeof AuthedDashboardClientsClientIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/forms/$formId/edit': {
      id: '/_authed/dashboard/forms/$formId/edit'
      path: '/forms/$formId/edit'
      fullPath: '/dashboard/forms/$formId/edit'
      preLoaderRoute: typeof AuthedDashboardFormsFormIdEditRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
  }
}

interface AuthedDashboardRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardClientsClientIdRoute: typeof AuthedDashboardClientsClientIdRoute
  AuthedDashboardFormsNewRoute: typeof AuthedDashboardFormsNewRoute
  AuthedDashboardSubmissionsSubmissionIdRoute: typeof AuthedDashboardSubmissionsSubmissionIdRoute
  AuthedDashboardVisitsVisitIdRoute: typeof AuthedDashboardVisitsVisitIdRoute
  AuthedDashboardCalendarIndexRoute: typeof AuthedDashboardCalendarIndexRoute
  AuthedDashboardClientsIndexRoute: typeof AuthedDashboardClientsIndexRoute
  AuthedDashboardFormsIndexRoute: typeof AuthedDashboardFormsIndexRoute
  AuthedDashboardSettingsIndexRoute: typeof AuthedDashboardSettingsIndexRoute
  AuthedDashboardStaffIndexRoute: typeof AuthedDashboardStaffIndexRoute
  AuthedDashboardSubmissionsIndexRoute: typeof AuthedDashboardSubmissionsIndexRoute
  AuthedDashboardTreatmentsIndexRoute: typeof AuthedDashboardTreatmentsIndexRoute
  AuthedDashboardVisitsIndexRoute: typeof AuthedDashboardVisitsIndexRoute
  AuthedDashboardFormsFormIdEditRoute: typeof AuthedDashboardFormsFormIdEditRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardClientsClientIdRoute: AuthedDashboardClientsClientIdRoute,
  AuthedDashboardFormsNewRoute: AuthedDashboardFormsNewRoute,
  AuthedDashboardSubmissionsSubmissionIdRoute:
    AuthedDashboardSubmissionsSubmissionIdRoute,
  AuthedDashboardVisitsVisitIdRoute: AuthedDashboardVisitsVisitIdRoute,
  AuthedDashboardCalendarIndexRoute: AuthedDashboardCalendarIndexRoute,
  AuthedDashboardClientsIndexRoute: AuthedDashboardClientsIndexRoute,
  AuthedDashboardFormsIndexRoute: AuthedDashboardFormsIndexRoute,
  AuthedDashboardSettingsIndexRoute: AuthedDashboardSettingsIndexRoute,
  AuthedDashboardStaffIndexRoute: AuthedDashboardStaffIndexRoute,
  AuthedDashboardSubmissionsIndexRoute: AuthedDashboardSubmissionsIndexRoute,
  AuthedDashboardTreatmentsIndexRoute: AuthedDashboardTreatmentsIndexRoute,
  AuthedDashboardVisitsIndexRoute: AuthedDashboardVisitsIndexRoute,
  AuthedDashboardFormsFormIdEditRoute: AuthedDashboardFormsFormIdEditRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ClientRouteChildren {
  ClientClientCalendarRoute: typeof ClientClientCalendarRoute
  ClientClientChatRoute: typeof ClientClientChatRoute
  ClientClientProfileRoute: typeof ClientClientProfileRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientClientCalendarRoute: ClientClientCalendarRoute,
  ClientClientChatRoute: ClientClientChatRoute,
  ClientClientProfileRoute: ClientClientProfileRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  RegisterClientRoute: RegisterClientRoute,
  FTokenRoute: FTokenRoute,
  FTokenSuccessRoute: FTokenSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
